import streamlit as st
import pandas as pd
import joblib
import shap
import matplotlib.pyplot as plt

# -------------------------
# Load trained AI model
# -------------------------

model = joblib.load("TractionScore_AI.pkl")

# Representative background dataset used to train the explainer
background = pd.read_csv("TractionScore_Cleaned.csv")

explainer = shap.LinearExplainer(model, background)

# -------------------------
# Page setup
# -------------------------

st.set_page_config(
    page_title="TractionScore AI",
    page_icon="🧬"
)


st.title("TractionScore AI")
st.image(
    "images/Traction Score AI Logo.png",
    width=180
)
st.sidebar.markdown("Pilot research prototype")
st.image(
    "images/1. Traction alopecia.png",
    caption="Common patterns of traction alopecia.",
    use_container_width=True
)
st.warning(
    "Privacy Notice: Your responses are used only to calculate your result during this session. "
    "No names, email addresses, dates of birth, or other personally identifiable information are requested."
)
st.caption("Disclaimer: This tool provides a screening estimate based on reported hair-care practices and is not a diagnosis of traction alopecia.")

st.write("""
### Check your risk for traction alopecia

TractionScore AI is a research-based screening tool that estimates your likelihood of having clinically significant traction alopecia based on your hair-care practices and scalp symptoms.

It is designed to help identify people who may benefit from a professional scalp assessment. It is **not** a medical diagnosis.
""")

st.info(
    "Please answer the questions as accurately as possible. "
    "Your estimate is only as reliable as the information you provide."
)

# -------------------------
# Patient questions
# -------------------------


age = st.number_input(
    "How old are you (years)?",
    min_value=5,
    max_value=100,
    value=25
)


hairstyle_days = st.number_input(
    "On average, how many days do you keep one hairstyle before changing it?",
    min_value=0,
    max_value=365,
    value=14
)


relaxer_answer = st.radio(
    "Do you currently use chemical hair relaxers or perm texturizers?",
    [
        "No",
        "Yes"
    ]
)


if relaxer_answer == "Yes":
    relaxer_use = 1
else:
    relaxer_use = 0



relaxer_frequency = st.number_input(
    "How many times per year do you chemically relax or touch up your hair?",
    min_value=0,
    max_value=30,
    value=0
)


age_first_relaxed = st.number_input(
    "At what age did you first start chemically relaxing your hair?",
    min_value=0,
    max_value=100,
    value=0
)


professional_stylist = st.number_input(
    "Out of your last 10 hairstyles, how many were done by a professional stylist?",
    min_value=0,
    max_value=10,
    value=5
)


headgear_hours = st.number_input(
    "Average weekly hours wearing tight headgear?",
    min_value=0,
    max_value=168,
    value=0
)


heat_styling_monthly = st.number_input(
    "How many times per month are heat styling tools applied?",
    min_value=0,
    max_value=100,
    value=0
)



symptom_answer = st.radio(
    "After hairstyles, do you experience pain, tenderness, severe itching, pimples, or sores?",
    [
        "No",
        "Yes"
    ]
)


if symptom_answer == "Yes":
    scalp_symptoms = 1
else:
    scalp_symptoms = 0



pain_duration_days = st.number_input(
    "If you experience pain, how many days does discomfort last?",
    min_value=0,
    max_value=365,
    value=0
)



# -------------------------
# Prediction
# -------------------------


if st.button("Calculate TractionScore"):

    patient_data = pd.DataFrame({

        "age":[age],
        "hairstyle_days":[hairstyle_days],
        "relaxer_use":[relaxer_use],
        "relaxer_frequency":[relaxer_frequency],
        "age_first_relaxed":[age_first_relaxed],
        "professional_stylist":[professional_stylist],
        "headgear_hours":[headgear_hours],
        "heat_styling_monthly":[heat_styling_monthly],
        "scalp_symptoms":[scalp_symptoms],
        "pain_duration_days":[pain_duration_days]

    })

    shap_values = explainer(patient_data)

    prediction = model.predict(patient_data)[0]

    probability = model.predict_proba(patient_data)[0][1]


    st.divider()

    st.subheader("Your Screening Result")


    st.metric(
        "Estimated likelihood",
        f"{probability*100:.1f}%"
    )


    st.caption(
        "This percentage is an estimate generated by the AI model. "
        "It does not confirm whether you have traction alopecia."
    )


    st.divider()

    st.subheader("What influenced your result?")

    st.write(
        "TractionScore AI looks at the combination of your answers to estimate your likelihood of traction alopecia. "
        "Some responses increase the estimated likelihood while others decrease it."
    )


    st.caption(
        "These factors helped the AI make its estimate. "
        "They should not be interpreted as proof that any one factor caused your result."
    )
# -------------------------
# SHAP explanation plot
# -------------------------

st.write("### AI explanation")

fig, ax = plt.subplots(figsize=(8,5))

shap.plots.waterfall(
    shap_values[0],
    max_display=10,
    show=False
)

st.pyplot(fig)    


    if prediction == 1:

        st.error(
            """There is a higher estimated likelihood that your responses are consistent with clinically significant traction alopecia.

Consider arranging an assessment with a dermatologist or another healthcare professional experienced in hair and scalp disorders, especially if you have persistent hair thinning, scalp pain, or patches of hair loss."""
        )

        st.subheader("Next steps")

        st.markdown(
            """
            - Avoid hairstyles that cause pain or scalp tenderness.
            - Reduce prolonged tight hairstyles.
            - Alternate protective hairstyles.
            - Allow recovery periods between styles.
            - Reduce frequent chemical relaxing.
            - Minimize excessive heat exposure.
            - Seek professional evaluation if thinning progresses.
            """
        )


    else:

        st.success(
            """Your responses suggest a lower estimated likelihood of clinically significant traction alopecia.

Continue practising healthy hair-care habits and seek medical advice if you notice increasing hair thinning, persistent scalp discomfort, or other concerning changes."""
        )

        st.subheader("Hair health recommendations")

        st.markdown(
            """
            - Continue gentle hair-care practices.
            - Avoid painful hairstyles.
            - Monitor for changes in hair density.
            - Maintain scalp health.
            """
        )
st.divider()

st.subheader("Help improve TractionScore AI")

st.write(
    "You can help improve future versions of this research tool by completing our anonymous feedback questionnaire."
)

st.image(
    "images/6. TractionScore AI QR code.png",
    width=250
)

st.caption("Scan the QR code to access the questionnaire.")

st.divider()

st.caption(
    "TractionScore AI is a research screening tool developed to estimate the likelihood of clinically significant traction alopecia based on self-reported information. "
    "It is not a diagnostic test and should not replace assessment by a qualified healthcare professional. "
    "If you have ongoing hair loss, scalp pain, sores, or other concerns, please seek medical advice."
)
