name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # Add your build and deploy steps here
      - name: Deploy to Server
        run: ./deploy.sh
        env:
          API_KEY: ${{ secrets.MY_DEPLOY_KEY }}
